### ISSUE TITLE
DAO Classes

### ISSUE THREAD

**Issue by hardingadonis** [hardingadonis/zhi#3]
Writing DAO classes for Zhi:
- [x] Wallet
- [x] #6
  - [x] TransferTransaction
  - [x] IncomeTransaction
  - [x] ExpenseTransaction
- [x] IncomeCategory
- [x] ExpenseCategory
- [x] Target
- [x] Debt

**Comment by georgii-musikhin** [comment]
What technology do you want to use for your DAO classes? JDBC or Spring JDBC or some ORM?

**Comment by hardingadonis** [comment]
> What technology do you want to use for your DAO classes? JDBC or Spring JDBC or some ORM?

Wow, I don't think will using ORM or something like that. I just write code manually. I will use DAO Interface like this:

```java
public interface DAO<T> {
    public List<T> getAll();
    
    public Optional<T> get(Integer ID);
    
    public void insert(T obj);
    
    public void delete(T obj);
    
    public void update(T obj);
}
```

**Comment by hardingadonis** [comment]
Done
